config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  get '/shared_lists' => 'lists#shared_lists'
  post 'lists/delete_shared' => 'lists#delete_shared'
  get '/auth/:provider/callback' => 'sessions#create'
  get '/sessions/logout' => 'sessions#destroy'


  resources :users, except: [:index, :new]
  resources :sessions
  resources :items
  resources :lists do
    resources :items
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates_presence_of :description
  belongs_to :user
  belongs_to :list

  def complete?
    self.completion==true
  end

  def incomplete?
    self.completion==false
  end

end

app/models/list.rb
class List < ApplicationRecord
  validates_presence_of :name
  has_many :items
  # , -> { order(created_at: :desc) }, dependent: :destroy
    # , -> { order(completion: :asc) }
  belongs_to :user
  has_many :shared_lists, dependent: :destroy
  has_many :users, through: :shared_lists
end

app/models/shared_list.rb
class SharedList < ApplicationRecord
  belongs_to :user
  belongs_to :list
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password


  validates_presence_of :username
  validates :username, uniqueness: { case_sensitive: false }

  validates :password, on: :create, presence: true, length: 6..32
  has_many :items, dependent: :destroy


  has_many :lists, dependent: :destroy
  has_many :shared_lists, dependent: :destroy
  has_many :lists_shared, through: :shared_lists, source: :list



  def all_lists
    self.lists + self.lists_shared
  end

  def self.find_or_create_by_omniauth(auth_hash)
    oauth_email=auth_hash['info']['email']
    username=auth_hash['info']['nickname']
    # image= auth_hash['info']['image']
    # location = auth_hash['extra']['location']
    self.where(email: auth_hash['info']['email']).first_or_create do |user|
    user.password=SecureRandom.hex
    # user.image=auth_hash['extra']['raw_info']['avatar_url']
    # user.location=auth_hash['extra']['raw_info']['location']
    user.username=auth_hash['info']['nickname']
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :user_authorized
  def current_user

    User.find(session[:user_id]) if session[:user_id]
  end

  def user_authorized
    redirect_to :root unless session[:user_id]
  end

  def user_logged_in
    redirect_to lists_path if session[:user_id]
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
   before_action :user_authorized
  def create
    print 'this is the function i am hitting'
    @list = List.find(params[:list_id])
    # @item = @list.items.create(item_params)
    # @item = @list.items.build(item_params)
    # @item.save
    # the above works just like the code below
    @item=Item.create(item_params.merge(list: @list, user: current_user))

    if @item.save
      respond_to do |f|
             f.html {redirect_to list_path(@list)}
             f.json {render :json => @item}
           end
         else
           render "lists/show"
         end
       end

  def update
   @item = Item.find(params[:id])
   @item.update(item_params)

   redirect_to list_path(@item.list)
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    respond_to do |f|
      f.json {render :json => @item}
      f.html {redirect_to list_path(@item.list)}
    end
  end

  private

    def item_params
      params.require(:item).permit(:description, :completion)
    end

end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
   before_action :user_authorized

  def index
    @list = List.new
    @lists = List.where(user: current_user)
  end

  def show
    @list = List.find(params[:id])
    # @list.items.order('created_at ASC')
    @user=current_user
    if @list.user==@user || @list.users.include?(@user)
      @item=Item.new
    else
      redirect_to lists_path
    end
  end


  def create
    @user=current_user
    @list = @user.lists.build(list_params)
    if @list.save
      redirect_to list_url(@list)
    else
      @lists = List.where(user: current_user)
      render :index
    end
  end

  def shared_lists
    @lists = current_user.lists_shared
  end

  def destroy
    # raise params.inspect
    list=List.find(params[:id])

    list.destroy
    redirect_to :back
  end

  def edit
    @share=SharedList.new
    @users=User.where.not(id: current_user.id)
    @list=List.find(params[:id])
    @user_ids = @list.user_ids
  end

  def update
    list=List.find(params[:id])
    user=User.find(params[:user_id])
    shared=SharedList.find_by(list: list, user: user)
    if shared
      shared.delete
    else
      SharedList.create(list:list, user: user)
    end
    redirect_to :back
  end

  def delete_shared
    @list=List.find(params[:id])
    @shared=SharedList.find_by(list: @list, user: current_user)
    @shared.destroy

    redirect_to :back

  end

  # def create_shared_list
  #   @list=List.find(params[:list])
  #   @user=User.find(params[:user])
  #   @shared_list=SharedList.new(list: @list, user: @user)
  #   redirect_to lists_path
  # end

  private
    def list_params
      params.require(:list).permit(:name, :user)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create

    if auth_hash=request.env['omniauth.auth']
      user= User.find_or_create_by_omniauth(auth_hash)
      session[:user_id]=user.id
      redirect_to lists_path
      #
      # oauth_email=request.env['omniauth.auth']['info']['email']
      # username=request.env['omniauth.auth']['info']['nickname']
      # image= request.env['omniauth.auth']['info']['image']
      # location = request.env['omniauth.auth']['extra']['location']
      # if user=User.find_by(email: oauth_email)
      #   session[:user_id]=user.id
      #   redirect_to users_path
      #
      # else
      #   user=User.new(email: oauth_email, password: SecureRandom.hex, username:username )
      #   if user.save
      #   session[:user_id]=user.id
      #
      #   redirect_to users_path
      # end
      #
      # end
    else
      user=User.find_by(username: user_params[:username])

      if user==nil
        flash[:username]='Invalid username'
      end
      if user && user.authenticate(user_params[:password])
        session[:user_id]=user.id
        redirect_to lists_path
      else
        flash[:password]='Invalid password'
        redirect_to :root
      end
    end
  end

  def destroy
    reset_session
    redirect_to :root
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :user_logged_in, only: [:new]

  def new
    @user=User.new
  end

  def create
    @user= User.create(user_params)
    if @user.valid?
      session[:user_id]=@user.id
      redirect_to lists_path
    else
      flash[:errors]= @user.errors.full_messages
      render :new
    end
  end

  def edit

  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      flash[:errors]= @user.errors.full_messages
      redirect_to :back
    end
  end

  def show
  end

  def set_user
   @user = User.find(session[:user_id])
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LastOff</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/edit.html.erb
<section class="todoapp">
  <header class="header">
    <h1>Share Your List</h1>
    <ul class="todo-list">
      <li>
        <div class="view">
          <label class="placeholder">Share with the following users...</label>
      </li>
    </ul>
  </header>

  <section class="main">
    <ul class="todo-list">
      <% @users.each do |user| %>
        <li class="share">
          <div class="view">
          <form class="" action="/lists/<%= @list.id %>" method="post">
            <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
            <input type="hidden" name="_method" value="patch">
            <input type="hidden" name="user_id" value="<%= user.id %>">
                <% if @user_ids.include? user.id %>
                  <input type="checkbox" class="toggle" checked>
                <% else %>
                  <input type="checkbox" class="toggle">
                <% end %>
                <label><%=user.username%></label>
          </form>
        </div>
      </li>
      <% end %>
    </ul>
  </section>


  <footer class="footer" style="display: block;">
    <span class="todo-count">Shared with <%=pluralize(@user_ids.count, 'user')%></span>
    	<ul class="filters">
        <li>
          <a href="/lists">Your Lists</a>
        </li>
        <li>
          <a href="/shared_lists">Shared Lists</a>
        </li>
        <li>
          <a href="/sessions/logout">Logout</a>
        </li>
    	</ul>
    	<button class="clear-completed" style="display: none;"></button>

    </footer>
</section>

app/views/lists/index.html.erb
<section class="todoapp">
  <header class="header">
    <h1>Your Lists</h1>
    <%= form_for(@list) do |f| %>
    <%if @list.errors[:name].present?%>
      <%= f.text_field :name, :class => "new-todo", :placeholder => "List must have a name...", :autofocus=>""%>
      <%else%>
      <%= f.text_field :name, :class => "new-todo", :placeholder =>"Enter a new list name...", :autofocus=>""%>
      <%end%>
      <%= f.submit :style => "display: none" %>
    <% end %>
  </header>
  <section class="main">
    <ul class="todo-list">
      <% @lists.each do |list| %>
      <li>
        <div class="view">
          <label><%= link_to list.name, list_path(list) %></label>
              <!-- <%= link_to '', lists_path(list), :method => "delete", :class => "destroy" %> -->
              <%=form_tag(list_path(list), :method=> :delete) do %>
                  <button type='submit' class='destroy'></button>
                  <% end %>
        </div>
      </li>
      <% end %>
    </ul>
  </section>
  <footer class="footer" style="display: block;">
  				<span class="todo-count"><%=pluralize(@lists.count, 'list')%></span>
  				<ul class="filters">
  					<li>
  						<a href="#/" class="selected">Your Lists</a>
  					</li>
  					<li>
  						<a href="/shared_lists">Shared Lists</a>
  					</li>
  					<li>
  						<a href="/sessions/logout">Logout</a>
  					</li>
  				</ul>
  				<button class="clear-completed" style="display: none;"></button>
  			</footer>
</section>

app/views/lists/shared_lists.html.erb
<section class="todoapp">
  <header class="header">
    <h1>Shared Lists</h1>
    <ul class="todo-list">
      <li>
        <div class="view">
        <label class='placeholder'>Your Shared Lists</label>
      </li>
    </ul>
  </header>
  <section class="main">

    <ul class="todo-list">
      <% @lists.each do |list| %>
      <li>
        <div class="view">
          <label><%= link_to list.name, list_path(list) %> <span class='right placeholder'> shared by <%=list.user.username%></span></label>
              <!-- <%= link_to '', lists_path(list), :method => "delete", :class => "destroy" %> -->
                  <form action='/lists/delete_shared' method='post'>

                    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
                      <input type="hidden" name="_method" value="destroy">
                      <input type="hidden" name="id" value="<%=list.id%>">
                    <button type='submit' class='destroy'></button>
                  </form>
        </div>
      </li>
      <% end %>
    </ul>
  </section>
  <footer class="footer" style="display: block;">
  				<span class="todo-count"><%=pluralize(@lists.count, 'list')%></span>
  				<ul class="filters">
  					<li>
  						<a href="/lists">Your Lists</a>
  					</li>
  					<li>
  						<a href="/shared_lists" class="selected">Shared Lists</a>
  					</li>
  					<li>
  						<a href="/sessions/logout">Logout</a>
  					</li>
  				</ul>
  				<button class="clear-completed" style="display: none;"></button>
  			</footer>
</section>

app/views/lists/show.html.erb
<section class="todoapp">
  <header class="header">
    <h1><%= @list.name %></h1>
    <%= form_for([@list, @item]) do |f| %>
      <%= f.text_field :description, :class => "new-todo", :placeholder => (@item.errors.full_messages_for(:description).first || "Enter a new item..."), :autofocus=>""%>

      <%= f.submit :style => "display: none", :id=>'to-do-submit', :data => { :disabled_with => false } %>
    <% end %>
  </header>
  <section class="main">
    <ul class="todo-list">
      <%@list.items.each do |item|%>
       <li class="<%= "completed" if item.completion %>">
        <div class="view">
          <%= form_for([@list, item]) do |f| %>
            <%= f.check_box :completion, :class => "toggle", :checked => (item.completion) %>
          <% end %>
          <label><%=item.description%></label>
          <%if item.user == @user%>

          <%=form_tag(list_item_path(item.list, item), :method=> :delete) do %>
              <button type='submit' class='destroy' ></button>
            <% end %>
          <% end %>
        </div>
      </li>
      <%end%>
    </ul>
  </section>


  <footer class="footer" style="display: block;">
  				<span class="todo-count"><%=pluralize(@list.items.count, 'item')%></span>
  				<ul class="filters">
            <li>
  						<a href="/lists">Your Lists</a>
  					</li>
            <%if @list.user==@user%>
    					<li>
    						<a href="/lists/<%=@list.id%>/edit">Share List</a>
    					</li>
              <%else%>
              <li>
    						<a href="/shared_lists">Shared Lists</a>
    					</li>
            <%end%>

  					<li>
  						<a href="/sessions/logout">Logout</a>
  					</li>
  				</ul>
  			 <button class="clear-completed" style="display: none;"></button>
  			</footer>
</section>


<script id="item-template" type="text/x-handlebars-template">
  <li class="item" id="item_{{id}}">
    <div class="view">
      <form class="edit_item" id="edit_item_{{id}}" action="/lists/<%= @list.id %>/items/{{id}}" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓">
        <input type="hidden" name="_method" value="patch">
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
        <input name="item[status]" type="hidden" value="0"><input class="toggle" type="checkbox" value="1" name="item[status]" id="item_status"></form>

      <label>{{description}}</label>

      <form class="button_to" method="post" action="/lists/<%= @list.id %>/items/{{id}}">
        <input type="hidden" name="_method" value="delete">
        <button type='submit' class='destroy'></button>
        <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
      </form>
    </div>
  </li>
</script>

app/views/users/_form.html.erb
<section class="todoapp">
  <section class="main">
    <h1>Welcome to LastOff!</h1>
    <ul class="todo-list">
      <li>
        <div class="view">
          <label>Register</label>
          </li>
          <%= form_for(user) do |f| %>
          <li>
            <%= f.text_field :username, :class => "new-todo", :placeholder => (@user.errors.full_messages_for(:username).first || "Username"), :autofocus=>""%>
          </li>

          <li>
            <%= f.password_field :password, :class => "new-todo", :placeholder => (@user.errors.full_messages_for(:password).first || "Password"), :autofocus=>""%>
          </li>
          <li>
              <%= f.password_field :password_confirmation, :class => "new-todo", :placeholder => (@user.errors.full_messages_for(:password_confirmation).first || "Password Confirmation"), :autofocus=>""%>
          </li>
    </ul>
      <%= f.submit :style => "display: none" %>
    <% end %>
    <ul class="todo-list">
      <li>
        <div class="view">
          <label>Login</label>
        </div>
      </li>
      <form action='/sessions' method='post'>
        <input type='hidden' name='authenticity_token' value="<%=form_authenticity_token%>">
        <input type='text' class="new-todo" placeholder=" <%= flash[:username] || "Username" %>" autofocus="" name='user[username]'>
        <li>
          <input type='password' class="new-todo" placeholder='<%= flash[:password] || "Password" %>' autofocus="" name='user[password]'>
        </li>
        <input type='submit' value='Login' style = "display: none">
      </form>
    </ul>
  </section>

  <footer class="footer" style="display: block;">
  	<ul class="filters">
  		<li>
  			<%= link_to('Log in with Github!', '/auth/github') %>
  		</li>
  	</ul>
  	<button class="clear-completed" style="display: none;"></button>
  </footer>
</section>

app/views/users/new.html.erb
<%= render partial: "users/form", locals: {user: @user} %>